mergeInto(LibraryManager.library,{
CounselCueWeb_Initialize:function(op,ap){
let S=window.CounselCueWeb={o:UTF8ToString(op),a:UTF8ToString(ap).replace(/\/$/,""),on:false,i:0};
let css=document.createElement("style");css.textContent="#cci{position:fixed;z-index:60;left:50%;bottom:16px;transform:translateX(-50%);width:min(65vw,1040px);display:none;gap:8px;font-family:'Malgun Gothic',sans-serif}#cci textarea{flex:1;height:58px;resize:none;box-sizing:border-box;border:2px solid #a7d4bb;border-radius:14px;background:#faf8f2;padding:13px 16px;font-size:17px;outline:none;box-shadow:0 8px 28px #0005}.ccb{height:58px;border:0;border-radius:14px;padding:0 17px;background:#347a5d;color:#fff;font-size:16px;font-weight:700}.mic{background:#835b50}.mic.on{background:#b84d4d;box-shadow:0 0 0 7px #b84d4d44}#ccn{position:absolute;left:8px;bottom:66px;color:#fff;background:#173b30ee;border-radius:20px;padding:5px 10px;font-size:11px}#cch{position:fixed;z-index:61;left:50%;top:12px;transform:translateX(-50%);border:1px solid #fff7;border-radius:20px;background:#173b30ee;color:#fff;padding:7px 12px;font-weight:700}#cct{position:fixed;inset:0;z-index:100;display:none;font-family:'Malgun Gothic',sans-serif;pointer-events:none}#ccs{position:fixed;border:3px solid #f3c778;border-radius:18px;box-shadow:0 0 0 9999px #040f0cc9,0 0 28px #f3c778;transition:.25s}#ccp{position:fixed;width:370px;max-width:calc(100vw - 32px);box-sizing:border-box;background:#faf6ec;border-radius:18px;padding:20px 22px;box-shadow:0 16px 46px #0007;pointer-events:auto}#ccp h3{margin:0 0 8px;color:#245e47}#ccp p{line-height:1.5}.ctb{border:0;border-radius:9px;padding:9px 13px;font-weight:700}.next{float:right;background:#347a5d;color:white}@media(max-width:800px){#cci{width:calc(100vw - 18px);bottom:8px}.ccb{padding:0 10px}.lbl{display:none}}";document.head.appendChild(css);
let r=document.createElement("div");r.id="cci";r.innerHTML='<span id="ccn">AI 생성 내담자 음성 · 원음 미저장</span><textarea placeholder="응답을 입력하거나 마이크를 누르세요…"></textarea><button class="ccb mic">● <span class="lbl">말하기</span></button><button class="ccb send">응답하기</button>';document.body.appendChild(r);S.r=r;S.x=r.querySelector("textarea");let m=r.querySelector(".mic"),b=r.querySelector(".send"),ch=()=>SendMessage(S.o,"OnWebTextChanged",S.x.value),go=()=>{let v=S.x.value.trim();if(S.on&&v)SendMessage(S.o,"OnWebTextSubmitted",v)};S.x.oninput=ch;S.x.onkeydown=e=>{if(e.key=="Enter"&&!e.shiftKey&&!e.isComposing){e.preventDefault();go()}};b.onclick=go;
let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(R){let q=new R();q.lang="ko-KR";q.interimResults=true;q.onstart=()=>m.classList.add("on");q.onresult=e=>{let t="";for(let j=e.resultIndex;j<e.results.length;j++)t+=e.results[j][0].transcript;S.x.value=t;ch()};q.onend=()=>{m.classList.remove("on");S.x.focus()};q.onerror=()=>m.classList.remove("on");m.onclick=()=>{try{q.start()}catch(e){q.stop()}}}else{m.disabled=true;m.title="Chrome 또는 Edge를 사용하세요."}
let t=document.createElement("div");t.id="cct";t.innerHTML='<div id="ccs"></div><div id="ccp"><h3></h3><p></p><button class="ctb skip">건너뛰기</button><button class="ctb next">다음</button></div>';document.body.appendChild(t);let h=document.createElement("button");h.id="cch";h.textContent="? 사용 안내";document.body.appendChild(h);let sp=t.querySelector("#ccs"),p=t.querySelector("#ccp"),nx=t.querySelector(".next"),er=e=>{let z=e.getBoundingClientRect();return[z.left,z.top,z.width,z.height]},ss=[["내담자의 표정과 자세를 관찰하세요","얼굴 근육, 시선, 움직임과 말의 내용을 함께 보세요.",()=>[innerWidth*.31,innerHeight*.12,innerWidth*.38,innerHeight*.56]],["관찰 줌을 활용하세요","오른쪽 줌 컨트롤로 표정과 제스처를 가까이 확인하세요.",()=>[innerWidth*.78,innerHeight*.24,innerWidth*.205,innerHeight*.08]],["한글 입력을 지원합니다","한글 조합, 붙여넣기, Shift+Enter 줄바꿈이 가능합니다.",()=>er(S.x)],["마이크로 응답하세요","최초 1회 브라우저 마이크 권한 승인이 필요합니다.",()=>er(m)],["감정 음성으로 답합니다","LLM 페르소나 답변이 ElevenLabs 음성으로 재생됩니다.",()=>er(b)]];
let draw=()=>{let s=ss[S.i],z=s[2]();Object.assign(sp.style,{left:z[0]-7+"px",top:z[1]-7+"px",width:z[2]+14+"px",height:z[3]+14+"px"});p.querySelector("h3").textContent=s[0];p.querySelector("p").textContent=s[1];p.style.left=Math.min(Math.max(16,z[0]+z[2]/2-185),innerWidth-386)+"px";p.style.top=(z[1]+z[3]+220<innerHeight?z[1]+z[3]+20:Math.max(16,z[1]-200))+"px";nx.textContent=S.i==4?"시작하기":"다음";t.style.display="block"},close=()=>{t.style.display="none";localStorage.setItem("counselcue-tour-v2","done")};nx.onclick=()=>{if(++S.i>4)close();else draw()};t.querySelector(".skip").onclick=close;h.onclick=()=>{S.i=0;draw()};S.show=()=>{if(!localStorage.getItem("counselcue-tour-v2")){S.i=0;draw()}};
},
CounselCueWeb_SetEnabled:function(v){let S=window.CounselCueWeb;if(!S)return;S.on=!!v;S.r.style.display=S.on?"flex":"none";if(S.on){S.x.focus();setTimeout(S.show,400)}},
CounselCueWeb_SetText:function(p){let S=window.CounselCueWeb;if(S)S.x.value=UTF8ToString(p)},
CounselCueWeb_Speak:function(tp,ep){let S=window.CounselCueWeb;if(!S||!S.a)return;fetch(S.a+"/voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:UTF8ToString(tp),emotion:UTF8ToString(ep)})}).then(r=>{if(!r.ok)throw Error(r.status);return r.blob()}).then(x=>{if(S.au)S.au.pause();S.au=new Audio(URL.createObjectURL(x));S.au.play().catch(console.warn)}).catch(console.warn)}
});